import { useState, useEffect } from "react";

// ─── Minimal jsPDF-like PDF generator (pure JS, no CDN needed) ───
function generatePDF(itinerary, tripData) {
  const lines = [];
  lines.push("RAHBAR – SMART TRAVEL COMPANION");
  lines.push("═".repeat(40));
  lines.push(`Destination: ${tripData.destination}`);
  lines.push(`Dates: ${tripData.startDate} → ${tripData.endDate}`);
  lines.push(`Budget: PKR ${Number(tripData.budget).toLocaleString()}`);
  lines.push(`Interests: ${tripData.interests}`);
  lines.push("─".repeat(40));
  lines.push("YOUR PERSONALIZED ITINERARY");
  lines.push("─".repeat(40));
  itinerary.days.forEach((day) => {
    lines.push(`\n📅 ${day.title}`);
    day.activities.forEach((a) => lines.push(`  • ${a}`));
  });
  lines.push("\n─".repeat(40));
  lines.push("PACKING SUGGESTIONS");
  lines.push("─".repeat(40));
  itinerary.packing.forEach((p) => lines.push(`  ✓ ${p}`));
  lines.push("\n─".repeat(40));
  lines.push("BUDGET BREAKDOWN");
  lines.push("─".repeat(40));
  itinerary.budget.forEach((b) => lines.push(`  ${b.label}: PKR ${b.amount.toLocaleString()}`));
  lines.push("\n─".repeat(40));
  lines.push("CULTURAL TIPS & PHRASES");
  lines.push("─".repeat(40));
  itinerary.culturalTips.forEach((t) => lines.push(`  → ${t}`));
  lines.push("\n\nGenerated by Rahbar – Smart Travel Companion");
  lines.push("Your AI-Powered Personal Travel Guide");

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Rahbar_Trip_${tripData.destination.replace(/\s+/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Sample destination data ───
const DESTINATIONS = {
  Paris: {
    emoji: "🗼",
    days: [
      {
        title: "Day 1 – Arrival & Iconic Landmarks",
        activities: [
          "Check in to your hotel near Champs-Élysées",
          "Evening walk to the Eiffel Tower",
          "Dinner at a classic French bistro",
          "Night cruise on the Seine River",
        ],
      },
      {
        title: "Day 2 – Art, Culture & History",
        activities: [
          "Morning visit to the Louvre Museum",
          "Lunch at Café de Flore, Saint-Germain",
          "Explore Musée d'Orsay impressionist collection",
          "Stroll through Marais district",
        ],
      },
      {
        title: "Day 3 – Day Trip & Shopping",
        activities: [
          "Day trip to Palace of Versailles",
          "Afternoon shopping on Rue du Faubourg Saint-Honoré",
          "Visit Sainte-Chapelle stained glass chapel",
          "Farewell dinner at Montmartre",
        ],
      },
    ],
    packing: [
      "Light layers for variable weather",
      "Comfortable walking shoes",
      "Universal power adapter (Type E)",
      "Phrasebook / Google Translate app",
      "Rain jacket",
      "Camera / extra memory cards",
    ],
    budget: [
      { label: "Accommodation (3 nights)", amount: 45000 },
      { label: "Meals & Dining", amount: 18000 },
      { label: "Transportation", amount: 8000 },
      { label: "Attractions & Tours", amount: 12000 },
      { label: "Shopping & Souvenirs", amount: 10000 },
      { label: "Emergency Reserve", amount: 7000 },
    ],
    culturalTips: [
      "Greet with 'Bonjour' before any conversation – it's considered rude not to",
      "Tipping is appreciated but not mandatory (5–10%)",
      "Shops close on Sundays – plan your shopping accordingly",
      "Useful phrase: 'Parlez-vous anglais?' (Do you speak English?)",
      "Dress modestly when visiting churches and cathedrals",
    ],
  },
  Istanbul: {
    emoji: "🕌",
    days: [
      {
        title: "Day 1 – The Historic Heart",
        activities: [
          "Morning visit to Hagia Sophia",
          "Explore Topkapi Palace and its treasures",
          "Lunch in the Grand Bazaar",
          "Sunset at Sultanahmet Square with Blue Mosque view",
        ],
      },
      {
        title: "Day 2 – Bosphorus & Asian Side",
        activities: [
          "Bosphorus boat cruise at sunrise",
          "Cross to Kadıköy on the Asian side",
          "Street food tour – simit, balık ekmek, Turkish tea",
          "Evening at Ortaköy waterfront",
        ],
      },
      {
        title: "Day 3 – Bazaars & Hidden Gems",
        activities: [
          "Spice Bazaar (Mısır Çarşısı) shopping",
          "Visit Süleymaniye Mosque – fewer crowds, stunning views",
          "Hammam experience at a traditional bath house",
          "Rooftop dinner in Beyoğlu district",
        ],
      },
    ],
    packing: [
      "Modest clothing (cover shoulders & knees for mosques)",
      "Comfortable sandals (remove shoes at mosques)",
      "Scarf for women visiting religious sites",
      "Turkish Lira in cash for bazaars",
      "Sunscreen – summers are very hot",
      "Small backpack for daily explorations",
    ],
    budget: [
      { label: "Accommodation (3 nights)", amount: 28000 },
      { label: "Meals & Dining", amount: 10000 },
      { label: "Transportation", amount: 5000 },
      { label: "Attractions & Tours", amount: 8000 },
      { label: "Shopping & Souvenirs", amount: 9000 },
      { label: "Emergency Reserve", amount: 5000 },
    ],
    culturalTips: [
      "Remove shoes before entering any mosque",
      "Bargaining is expected in bazaars – start at 60% of the asking price",
      "Useful phrase: 'Teşekkürler' (Thank you)",
      "Avoid eating or drinking in public during Ramadan",
      "Tea (çay) is offered everywhere – refusing can seem rude",
    ],
  },
  Dubai: {
    emoji: "🌆",
    days: [
      {
        title: "Day 1 – Modern Marvels",
        activities: [
          "Burj Khalifa observation deck at sunset",
          "Dubai Mall – world's largest shopping centre",
          "Dubai Fountain show (runs every 30 min)",
          "Night drive along Sheikh Zayed Road",
        ],
      },
      {
        title: "Day 2 – Desert & Adventure",
        activities: [
          "Morning dune bashing in the Dubai desert",
          "Camel riding and sandboarding",
          "Traditional Bedouin camp lunch",
          "Stargazing in the desert at night",
        ],
      },
      {
        title: "Day 3 – Old Dubai & Waterways",
        activities: [
          "Abra (water taxi) ride across Dubai Creek",
          "Gold Souk and Spice Souk shopping",
          "Visit Al Fahidi Historical Neighbourhood",
          "Brunch at a Jumeirah Beach restaurant",
        ],
      },
    ],
    packing: [
      "Light, breathable clothing (extreme heat)",
      "Modest dress for public areas (cover shoulders & knees)",
      "Sunscreen SPF 50+ and sunglasses",
      "Comfortable walking shoes",
      "Swimwear for beach/pool",
      "Power bank – lots of photography",
    ],
    budget: [
      { label: "Accommodation (3 nights)", amount: 65000 },
      { label: "Meals & Dining", amount: 22000 },
      { label: "Transportation", amount: 12000 },
      { label: "Attractions & Tours", amount: 20000 },
      { label: "Shopping & Souvenirs", amount: 15000 },
      { label: "Emergency Reserve", amount: 10000 },
    ],
    culturalTips: [
      "Public displays of affection are illegal – be mindful",
      "Dress code is strictly enforced in malls and public spaces",
      "Useful phrase: 'Shukran' (Thank you in Arabic)",
      "Alcohol is only served in licensed hotels and restaurants",
      "Friday is the holy day – many places open late or are closed",
    ],
  },
  Lahore: {
    emoji: "🏯",
    days: [
      {
        title: "Day 1 – Walled City Wonders",
        activities: [
          "Morning at Badshahi Mosque – one of the world's largest",
          "Lahore Fort (Shahi Qila) and Sheesh Mahal",
          "Walk along the historic Walled City",
          "Evening food street in Gawalmandi",
        ],
      },
      {
        title: "Day 2 – Mughal Heritage & Gardens",
        activities: [
          "Shalimar Gardens UNESCO World Heritage Site",
          "Wazir Khan Mosque – intricate tile work",
          "Anarkali Bazaar shopping for clothes & fabric",
          "Lahore Museum and Kipling's Gun",
        ],
      },
      {
        title: "Day 3 – Modern Lahore & Cuisine",
        activities: [
          "Liberty Market and MM Alam Road café culture",
          "Minar-e-Pakistan – symbol of independence",
          "Traditional lunch at Butt Karahi",
          "Wagah Border flag-lowering ceremony at sunset",
        ],
      },
    ],
    packing: [
      "Salwar kameez or modest clothing",
      "Comfortable sandals for walking",
      "Dupatta/scarf for women",
      "Cash (PKR) – many places don't accept cards",
      "Hand sanitizer and personal medications",
      "Water bottle – stay hydrated",
    ],
    budget: [
      { label: "Accommodation (3 nights)", amount: 15000 },
      { label: "Meals & Dining", amount: 6000 },
      { label: "Transportation", amount: 3000 },
      { label: "Attractions & Tours", amount: 2000 },
      { label: "Shopping & Souvenirs", amount: 8000 },
      { label: "Emergency Reserve", amount: 3000 },
    ],
    culturalTips: [
      "Greet with 'Assalam o Alaikum' – warmly received everywhere",
      "Bargaining is standard in bazaars",
      "Dress conservatively, especially near religious sites",
      "Useful phrase: 'Kitne ka hai?' (How much is it?)",
      "Lahori hospitality is legendary – accept tea when offered",
    ],
  },
};

// ─── Styles ───
const styles = `
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=DM+Sans:wght@300;400;500;600&display=swap');

  :root {
    --sand: #F2E8D5;
    --deep: #1A1207;
    --amber: #C8840A;
    --gold: #E8A020;
    --terracotta: #C45C2E;
    --sage: #4A7C59;
    --sky: #3B82A0;
    --cream: #FAF5EC;
    --muted: #8B7355;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }
  
  body {
    font-family: 'DM Sans', sans-serif;
    background: var(--cream);
    color: var(--deep);
    overflow-x: hidden;
  }

  .display { font-family: 'Playfair Display', serif; }

  /* Scrollbar */
  ::-webkit-scrollbar { width: 6px; }
  ::-webkit-scrollbar-track { background: var(--sand); }
  ::-webkit-scrollbar-thumb { background: var(--amber); border-radius: 3px; }

  /* Navbar */
  .navbar {
    position: fixed; top: 0; left: 0; right: 0; z-index: 100;
    padding: 0 2rem;
    height: 70px;
    display: flex; align-items: center; justify-content: space-between;
    background: rgba(250, 245, 236, 0.92);
    backdrop-filter: blur(12px);
    border-bottom: 1px solid rgba(200, 132, 10, 0.15);
    transition: box-shadow 0.3s;
  }
  .navbar.scrolled { box-shadow: 0 4px 24px rgba(26,18,7,0.1); }
  .nav-logo { display: flex; align-items: center; gap: 10px; cursor: pointer; }
  .nav-logo-icon {
    width: 38px; height: 38px; border-radius: 10px;
    background: linear-gradient(135deg, var(--amber), var(--terracotta));
    display: flex; align-items: center; justify-content: center;
    font-size: 1.2rem; color: white;
  }
  .nav-logo-text { font-family: 'Playfair Display', serif; font-size: 1.4rem; font-weight: 700; color: var(--deep); }
  .nav-links { display: flex; align-items: center; gap: 0.5rem; }
  .nav-link {
    padding: 0.5rem 1rem; border-radius: 8px;
    font-size: 0.9rem; font-weight: 500; cursor: pointer;
    border: none; background: none; color: var(--muted);
    transition: all 0.2s;
  }
  .nav-link:hover, .nav-link.active { color: var(--amber); background: rgba(200,132,10,0.08); }
  .nav-cta {
    padding: 0.5rem 1.2rem; border-radius: 8px;
    background: var(--amber); color: white;
    font-size: 0.9rem; font-weight: 600; cursor: pointer; border: none;
    transition: all 0.2s; box-shadow: 0 2px 8px rgba(200,132,10,0.3);
  }
  .nav-cta:hover { background: #b3720a; transform: translateY(-1px); box-shadow: 0 4px 16px rgba(200,132,10,0.4); }
  
  /* Mobile menu */
  .hamburger {
    display: none; flex-direction: column; gap: 5px;
    cursor: pointer; border: none; background: none; padding: 4px;
  }
  .hamburger span { width: 24px; height: 2px; background: var(--deep); border-radius: 2px; transition: 0.3s; }
  .mobile-menu {
    display: none; position: fixed; top: 70px; left: 0; right: 0;
    background: var(--cream); border-bottom: 1px solid rgba(200,132,10,0.15);
    flex-direction: column; padding: 1rem; z-index: 99;
    box-shadow: 0 8px 24px rgba(26,18,7,0.1);
  }
  .mobile-menu.open { display: flex; }
  .mobile-menu .nav-link { width: 100%; text-align: left; padding: 0.75rem 1rem; }

  @media (max-width: 768px) {
    .nav-links { display: none; }
    .hamburger { display: flex; }
  }

  /* Hero Section */
  .hero {
    min-height: 100vh;
    position: relative;
    display: flex; align-items: center;
    overflow: hidden;
    padding-top: 70px;
  }
  .hero-bg {
    position: absolute; inset: 0;
    background: 
      radial-gradient(ellipse 70% 60% at 80% 40%, rgba(200,132,10,0.12) 0%, transparent 60%),
      radial-gradient(ellipse 50% 50% at 20% 70%, rgba(196,92,46,0.1) 0%, transparent 50%),
      radial-gradient(ellipse 60% 40% at 50% 10%, rgba(59,130,160,0.08) 0%, transparent 50%),
      var(--cream);
  }
  .hero-pattern {
    position: absolute; inset: 0; opacity: 0.03;
    background-image: repeating-linear-gradient(45deg, var(--deep) 0, var(--deep) 1px, transparent 0, transparent 50%);
    background-size: 24px 24px;
  }
  .hero-content {
    position: relative; z-index: 2;
    max-width: 1200px; margin: 0 auto; padding: 4rem 2rem;
    display: grid; grid-template-columns: 1fr 1fr; gap: 4rem; align-items: center;
  }
  .hero-tag {
    display: inline-flex; align-items: center; gap: 8px;
    background: rgba(200,132,10,0.1); border: 1px solid rgba(200,132,10,0.2);
    color: var(--amber); padding: 0.4rem 1rem; border-radius: 100px;
    font-size: 0.82rem; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase;
    margin-bottom: 1.5rem;
  }
  .hero-title {
    font-family: 'Playfair Display', serif;
    font-size: clamp(2.8rem, 5vw, 4.2rem);
    line-height: 1.1; color: var(--deep); margin-bottom: 1.5rem;
  }
  .hero-title em { font-style: normal; color: var(--amber); }
  .hero-subtitle { font-size: 1.1rem; line-height: 1.7; color: var(--muted); margin-bottom: 2.5rem; max-width: 500px; }
  .hero-btns { display: flex; gap: 1rem; flex-wrap: wrap; }
  .btn-primary {
    padding: 0.9rem 2rem; border-radius: 12px;
    background: linear-gradient(135deg, var(--amber), var(--terracotta));
    color: white; font-size: 1rem; font-weight: 600; cursor: pointer; border: none;
    box-shadow: 0 4px 20px rgba(200,132,10,0.35);
    transition: all 0.3s; display: flex; align-items: center; gap: 8px;
  }
  .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 8px 28px rgba(200,132,10,0.45); }
  .btn-secondary {
    padding: 0.9rem 2rem; border-radius: 12px;
    background: transparent; border: 2px solid rgba(200,132,10,0.3);
    color: var(--amber); font-size: 1rem; font-weight: 600; cursor: pointer;
    transition: all 0.3s;
  }
  .btn-secondary:hover { background: rgba(200,132,10,0.08); border-color: var(--amber); }
  .hero-stats {
    display: flex; gap: 2rem; margin-top: 3rem; padding-top: 2rem;
    border-top: 1px solid rgba(200,132,10,0.15);
  }
  .hero-stat { }
  .hero-stat-num { font-family: 'Playfair Display', serif; font-size: 1.8rem; font-weight: 700; color: var(--deep); }
  .hero-stat-label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }

  /* Hero Visual */
  .hero-visual { position: relative; }
  .hero-card-main {
    background: white; border-radius: 24px; padding: 2rem;
    box-shadow: 0 20px 60px rgba(26,18,7,0.12);
    border: 1px solid rgba(200,132,10,0.1);
    animation: float 6s ease-in-out infinite;
  }
  @keyframes float {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-12px); }
  }
  .hero-card-dest {
    display: flex; align-items: center; gap: 12px; margin-bottom: 1.5rem;
    padding-bottom: 1.5rem; border-bottom: 1px solid var(--sand);
  }
  .dest-emoji { font-size: 2.5rem; }
  .dest-name { font-family: 'Playfair Display', serif; font-size: 1.4rem; font-weight: 700; }
  .dest-tag { font-size: 0.78rem; color: var(--sage); background: rgba(74,124,89,0.1); padding: 0.2rem 0.6rem; border-radius: 100px; }
  .hero-card-route { display: flex; flex-direction: column; gap: 12px; margin-bottom: 1.5rem; }
  .route-item { display: flex; align-items: center; gap: 10px; font-size: 0.88rem; }
  .route-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--amber); flex-shrink: 0; }
  .route-label { color: var(--muted); font-size: 0.78rem; }
  .hero-weather {
    display: flex; gap: 0.8rem;
  }
  .weather-chip {
    flex: 1; background: var(--sand); border-radius: 10px; padding: 0.6rem;
    text-align: center; font-size: 0.78rem;
  }
  .weather-chip strong { display: block; font-size: 1.1rem; }

  .hero-card-float {
    position: absolute; background: white; border-radius: 14px; padding: 0.8rem 1rem;
    box-shadow: 0 8px 24px rgba(26,18,7,0.1); border: 1px solid rgba(200,132,10,0.1);
    font-size: 0.8rem; white-space: nowrap;
  }
  .float-1 { top: -20px; right: -20px; animation: float 4s ease-in-out infinite 1s; }
  .float-2 { bottom: -20px; left: -20px; animation: float 5s ease-in-out infinite 0.5s; }
  .float-icon { margin-right: 6px; }

  @media (max-width: 768px) {
    .hero-content { grid-template-columns: 1fr; gap: 2rem; }
    .hero-visual { display: none; }
  }

  /* Features */
  .section { max-width: 1200px; margin: 0 auto; padding: 5rem 2rem; }
  .section-tag {
    display: inline-flex; align-items: center; gap: 8px;
    background: rgba(200,132,10,0.08); border: 1px solid rgba(200,132,10,0.15);
    color: var(--amber); padding: 0.35rem 0.9rem; border-radius: 100px;
    font-size: 0.78rem; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase;
    margin-bottom: 1rem;
  }
  .section-title {
    font-family: 'Playfair Display', serif;
    font-size: clamp(2rem, 3.5vw, 2.8rem); font-weight: 700;
    color: var(--deep); margin-bottom: 1rem; line-height: 1.2;
  }
  .section-sub { font-size: 1.05rem; color: var(--muted); max-width: 560px; line-height: 1.7; margin-bottom: 3rem; }

  .features-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; }
  @media (max-width: 1024px) { .features-grid { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 640px) { .features-grid { grid-template-columns: 1fr; } }

  .feature-card {
    background: white; border-radius: 20px; padding: 2rem;
    border: 1px solid rgba(200,132,10,0.08);
    box-shadow: 0 2px 12px rgba(26,18,7,0.04);
    transition: all 0.3s; cursor: default;
    position: relative; overflow: hidden;
  }
  .feature-card::before {
    content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px;
    background: linear-gradient(90deg, var(--amber), var(--terracotta));
    transform: scaleX(0); transform-origin: left; transition: transform 0.3s;
  }
  .feature-card:hover { transform: translateY(-4px); box-shadow: 0 12px 36px rgba(26,18,7,0.1); }
  .feature-card:hover::before { transform: scaleX(1); }
  .feature-icon {
    width: 52px; height: 52px; border-radius: 14px; margin-bottom: 1.2rem;
    display: flex; align-items: center; justify-content: center;
    font-size: 1.5rem;
  }
  .feature-title { font-family: 'Playfair Display', serif; font-size: 1.15rem; font-weight: 700; margin-bottom: 0.5rem; }
  .feature-desc { font-size: 0.9rem; color: var(--muted); line-height: 1.65; }

  /* How it works */
  .how-bg { background: var(--deep); color: white; }
  .how-section { max-width: 1200px; margin: 0 auto; padding: 5rem 2rem; }
  .how-section .section-title { color: white; }
  .how-section .section-sub { color: rgba(255,255,255,0.55); }
  .how-section .section-tag { background: rgba(200,132,10,0.2); border-color: rgba(200,132,10,0.3); }
  .steps-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1.5rem; }
  @media (max-width: 1024px) { .steps-grid { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 640px) { .steps-grid { grid-template-columns: 1fr; } }
  .step-card {
    background: rgba(255,255,255,0.05); border-radius: 20px; padding: 1.8rem;
    border: 1px solid rgba(255,255,255,0.08); transition: all 0.3s;
  }
  .step-card:hover { background: rgba(255,255,255,0.08); transform: translateY(-4px); }
  .step-num {
    font-family: 'Playfair Display', serif; font-size: 3rem; font-weight: 900;
    color: rgba(200,132,10,0.25); line-height: 1; margin-bottom: 1rem;
  }
  .step-title { font-size: 1rem; font-weight: 600; margin-bottom: 0.5rem; }
  .step-desc { font-size: 0.85rem; color: rgba(255,255,255,0.5); line-height: 1.6; }

  /* Destinations */
  .dest-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1.2rem; }
  @media (max-width: 1024px) { .dest-grid { grid-template-columns: repeat(2, 1fr); } }
  @media (max-width: 640px) { .dest-grid { grid-template-columns: 1fr; } }
  .dest-card {
    background: white; border-radius: 20px; padding: 2rem;
    border: 1px solid rgba(200,132,10,0.08);
    box-shadow: 0 2px 12px rgba(26,18,7,0.04);
    transition: all 0.3s; cursor: pointer; text-align: center;
  }
  .dest-card:hover { transform: translateY(-6px); box-shadow: 0 16px 40px rgba(26,18,7,0.12); border-color: rgba(200,132,10,0.2); }
  .dest-card-emoji { font-size: 3rem; margin-bottom: 1rem; display: block; }
  .dest-card-name { font-family: 'Playfair Display', serif; font-size: 1.2rem; font-weight: 700; margin-bottom: 0.3rem; }
  .dest-card-tag { font-size: 0.78rem; color: var(--muted); }
  .dest-card-badge {
    display: inline-block; margin-top: 0.8rem;
    background: rgba(200,132,10,0.08); color: var(--amber);
    padding: 0.25rem 0.7rem; border-radius: 100px; font-size: 0.75rem; font-weight: 600;
  }

  /* Planner Form */
  .planner-page { min-height: 100vh; padding-top: 70px; background: var(--cream); }
  .planner-container { max-width: 860px; margin: 0 auto; padding: 4rem 2rem; }
  .planner-header { text-align: center; margin-bottom: 3rem; }
  .form-card {
    background: white; border-radius: 24px; padding: 2.5rem;
    box-shadow: 0 8px 40px rgba(26,18,7,0.08); border: 1px solid rgba(200,132,10,0.1);
  }
  .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
  @media (max-width: 640px) { .form-grid { grid-template-columns: 1fr; } }
  .form-group { display: flex; flex-direction: column; gap: 0.5rem; }
  .form-group.full { grid-column: 1 / -1; }
  .form-label { font-size: 0.85rem; font-weight: 600; color: var(--deep); letter-spacing: 0.02em; }
  .form-input, .form-select, .form-textarea {
    padding: 0.85rem 1rem; border-radius: 12px;
    border: 1.5px solid rgba(200,132,10,0.2); background: var(--cream);
    font-family: 'DM Sans', sans-serif; font-size: 0.95rem; color: var(--deep);
    transition: all 0.2s; outline: none;
  }
  .form-input:focus, .form-select:focus, .form-textarea:focus {
    border-color: var(--amber); box-shadow: 0 0 0 3px rgba(200,132,10,0.1);
    background: white;
  }
  .form-textarea { resize: vertical; min-height: 100px; }
  .interest-chips { display: flex; flex-wrap: wrap; gap: 0.5rem; margin-top: 0.5rem; }
  .chip {
    padding: 0.4rem 0.9rem; border-radius: 100px; font-size: 0.82rem;
    border: 1.5px solid rgba(200,132,10,0.2); background: var(--cream);
    cursor: pointer; transition: all 0.2s; font-family: 'DM Sans', sans-serif;
    color: var(--muted);
  }
  .chip.selected { background: var(--amber); color: white; border-color: var(--amber); }
  .form-submit {
    width: 100%; padding: 1rem; border-radius: 14px; margin-top: 1.5rem;
    background: linear-gradient(135deg, var(--amber), var(--terracotta));
    color: white; font-size: 1rem; font-weight: 600; cursor: pointer; border: none;
    box-shadow: 0 4px 20px rgba(200,132,10,0.3); transition: all 0.3s;
    display: flex; align-items: center; justify-content: center; gap: 10px;
  }
  .form-submit:hover { transform: translateY(-2px); box-shadow: 0 8px 28px rgba(200,132,10,0.4); }
  .form-submit:disabled { opacity: 0.7; cursor: not-allowed; transform: none; }

  /* Loading */
  .loading-overlay {
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    padding: 4rem; gap: 1.5rem; text-align: center;
  }
  .spinner {
    width: 56px; height: 56px; border-radius: 50%;
    border: 3px solid var(--sand);
    border-top-color: var(--amber); border-right-color: var(--terracotta);
    animation: spin 0.9s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
  .loading-text { font-family: 'Playfair Display', serif; font-size: 1.2rem; color: var(--deep); }
  .loading-sub { font-size: 0.88rem; color: var(--muted); }
  .loading-steps { display: flex; gap: 0.5rem; margin-top: 0.5rem; }
  .loading-dot {
    width: 8px; height: 8px; border-radius: 50%; background: var(--sand);
    animation: pulse 1.2s ease-in-out infinite;
  }
  .loading-dot:nth-child(2) { animation-delay: 0.2s; }
  .loading-dot:nth-child(3) { animation-delay: 0.4s; }
  @keyframes pulse { 0%, 80%, 100% { background: var(--sand); } 40% { background: var(--amber); } }

  /* Dashboard / Itinerary */
  .dashboard-page { min-height: 100vh; padding-top: 70px; background: var(--cream); }
  .dashboard-container { max-width: 1100px; margin: 0 auto; padding: 3rem 2rem; }
  .dashboard-header {
    display: flex; align-items: flex-start; justify-content: space-between;
    flex-wrap: wrap; gap: 1.5rem; margin-bottom: 2.5rem;
  }
  .dashboard-title { font-family: 'Playfair Display', serif; font-size: 2rem; font-weight: 700; }
  .dashboard-sub { font-size: 0.9rem; color: var(--muted); margin-top: 0.3rem; }
  .download-btn {
    padding: 0.8rem 1.5rem; border-radius: 12px;
    background: var(--deep); color: white;
    font-size: 0.9rem; font-weight: 600; cursor: pointer; border: none;
    display: flex; align-items: center; gap: 8px; transition: all 0.2s;
  }
  .download-btn:hover { background: #2a1f0d; transform: translateY(-1px); }
  
  .dashboard-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; }
  @media (max-width: 900px) { .dashboard-grid { grid-template-columns: 1fr; } }

  .panel {
    background: white; border-radius: 20px; padding: 1.8rem;
    border: 1px solid rgba(200,132,10,0.08);
    box-shadow: 0 2px 12px rgba(26,18,7,0.04);
  }
  .panel-title {
    font-family: 'Playfair Display', serif; font-size: 1.15rem; font-weight: 700;
    margin-bottom: 1.2rem; display: flex; align-items: center; gap: 8px;
  }

  .day-block { margin-bottom: 1.5rem; }
  .day-label {
    font-size: 0.78rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--amber); margin-bottom: 0.7rem;
  }
  .activity-item {
    display: flex; align-items: flex-start; gap: 10px;
    padding: 0.6rem 0; border-bottom: 1px solid var(--sand); font-size: 0.9rem;
    color: var(--deep); line-height: 1.4;
  }
  .activity-item:last-child { border-bottom: none; }
  .activity-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--amber); flex-shrink: 0; margin-top: 6px; }

  .budget-item {
    display: flex; align-items: center; justify-content: space-between;
    padding: 0.7rem 0; border-bottom: 1px solid var(--sand); font-size: 0.88rem;
  }
  .budget-item:last-child { border-bottom: none; }
  .budget-label { color: var(--muted); }
  .budget-amount { font-weight: 600; color: var(--deep); }
  .budget-total {
    display: flex; align-items: center; justify-content: space-between;
    padding: 0.9rem 0 0; margin-top: 0.3rem;
    border-top: 2px solid var(--amber);
    font-weight: 700; font-size: 0.95rem;
  }
  .budget-bar { height: 6px; border-radius: 3px; background: var(--sand); margin: 0.4rem 0; overflow: hidden; }
  .budget-bar-fill { height: 100%; border-radius: 3px; background: linear-gradient(90deg, var(--amber), var(--terracotta)); transition: width 1s ease; }

  .tip-item {
    display: flex; gap: 10px; padding: 0.7rem 0;
    border-bottom: 1px solid var(--sand); font-size: 0.86rem; color: var(--deep); line-height: 1.5;
  }
  .tip-item:last-child { border-bottom: none; }
  .tip-arrow { color: var(--amber); flex-shrink: 0; font-weight: 700; }

  .pack-item {
    display: flex; align-items: center; gap: 10px;
    padding: 0.5rem 0; font-size: 0.88rem; color: var(--deep);
  }
  .pack-check { color: var(--sage); font-size: 1rem; flex-shrink: 0; }

  .alert-banner {
    background: linear-gradient(135deg, rgba(200,132,10,0.08), rgba(196,92,46,0.06));
    border: 1px solid rgba(200,132,10,0.2); border-radius: 14px; padding: 1rem 1.2rem;
    display: flex; gap: 10px; align-items: flex-start; margin-bottom: 1rem;
    font-size: 0.88rem;
  }
  .alert-icon { font-size: 1.1rem; flex-shrink: 0; }

  .new-plan-btn {
    padding: 0.75rem 1.5rem; border-radius: 12px; margin-top: 1.5rem;
    background: transparent; border: 2px solid rgba(200,132,10,0.2);
    color: var(--amber); font-size: 0.9rem; font-weight: 600; cursor: pointer;
    width: 100%; transition: all 0.2s;
  }
  .new-plan-btn:hover { background: rgba(200,132,10,0.06); border-color: var(--amber); }

  /* Footer */
  .footer { background: var(--deep); color: white; padding: 3rem 2rem 1.5rem; }
  .footer-inner { max-width: 1200px; margin: 0 auto; }
  .footer-top { display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 3rem; margin-bottom: 2.5rem; }
  @media (max-width: 768px) { .footer-top { grid-template-columns: 1fr; gap: 2rem; } }
  .footer-brand p { font-size: 0.88rem; color: rgba(255,255,255,0.45); line-height: 1.7; margin-top: 0.8rem; max-width: 300px; }
  .footer-col h4 { font-size: 0.85rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: var(--gold); margin-bottom: 1rem; }
  .footer-link {
    display: block; font-size: 0.88rem; color: rgba(255,255,255,0.45);
    cursor: pointer; margin-bottom: 0.5rem; transition: color 0.2s;
  }
  .footer-link:hover { color: rgba(255,255,255,0.85); }
  .footer-bottom {
    border-top: 1px solid rgba(255,255,255,0.08); padding-top: 1.5rem;
    display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 1rem;
  }
  .footer-copy { font-size: 0.82rem; color: rgba(255,255,255,0.3); }
  .footer-badges { display: flex; gap: 0.5rem; }
  .footer-badge {
    padding: 0.3rem 0.7rem; border-radius: 6px;
    background: rgba(255,255,255,0.06); font-size: 0.72rem;
    color: rgba(255,255,255,0.4);
  }

  /* Transitions */
  .page-enter { animation: pageIn 0.4s ease forwards; }
  @keyframes pageIn {
    from { opacity: 0; transform: translateY(16px); }
    to { opacity: 1; transform: translateY(0); }
  }

  /* Utility */
  .text-center { text-align: center; }
  .mt-1 { margin-top: 0.5rem; }
  .gradient-text {
    background: linear-gradient(135deg, var(--amber), var(--terracotta));
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  }
`;

// ─── Icons (simple SVG components) ───
const Icon = ({ name, size = 18, color = "currentColor" }) => {
  const icons = {
    compass: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg>,
    map: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"/><line x1="8" y1="2" x2="8" y2="18"/><line x1="16" y1="6" x2="16" y2="22"/></svg>,
    brain: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/></svg>,
    wallet: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/></svg>,
    alert: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
    cloud: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/></svg>,
    globe: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
    download: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
    arrow: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>,
    star: <svg width={size} height={size} viewBox="0 0 24 24" fill={color} stroke={color} strokeWidth="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>,
    check: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>,
    mail: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>,
    phone: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>,
    send: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>,
  };
  return icons[name] || null;
};

// ─── FEATURES DATA ───
const FEATURES = [
  { icon: "🗺️", color: "rgba(200,132,10,0.12)", title: "AI Itinerary Builder", desc: "Generates personalized day-by-day travel plans based on your budget, dates, and interests using advanced LLMs." },
  { icon: "💰", color: "rgba(74,124,89,0.12)", title: "Smart Budget Tracker", desc: "Track expenses in real time, get budget alerts, and receive cost-saving suggestions throughout your trip." },
  { icon: "⚠️", color: "rgba(196,92,46,0.12)", title: "Real-Time Alerts", desc: "Stay ahead of flight delays, weather changes, and emergencies with intelligent re-routing suggestions." },
  { icon: "🌍", color: "rgba(59,130,160,0.12)", title: "Cultural Intelligence", desc: "Get local customs, etiquette tips, and essential phrases to navigate any destination with confidence." },
  { icon: "🧳", color: "rgba(107,70,193,0.12)", title: "Smart Packing Guide", desc: "Weather-aware packing lists tailored to your destination, trip duration, and planned activities." },
  { icon: "🛫", color: "rgba(200,132,10,0.12)", title: "Flight & Weather Data", desc: "Powered by Aviation Edge and OpenWeatherMap APIs for accurate, real-time travel intelligence." },
];

const INTERESTS = ["Culture & History", "Food & Cuisine", "Adventure & Hiking", "Shopping", "Art & Museums", "Nature & Wildlife", "Beaches & Relaxation", "Nightlife", "Photography", "Architecture"];

// ─── MAIN APP ───
export default function RahbarApp() {
  const [page, setPage] = useState("home");
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [tripData, setTripData] = useState(null);
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState(0);

  const loadingMessages = [
    "Analyzing your travel preferences…",
    "Crafting your personalized itinerary…",
    "Checking weather & local events…",
    "Preparing cultural insights…",
  ];

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [page]);

  const navigate = (p) => { setPage(p); setMenuOpen(false); };

  const handlePlanSubmit = (data) => {
    setTripData(data);
    setLoading(true);
    setLoadingMsg(0);
    const interval = setInterval(() => setLoadingMsg(m => (m + 1) % loadingMessages.length), 1800);
    setTimeout(() => {
      clearInterval(interval);
      // Match destination to dataset or use Paris as default
      const key = Object.keys(DESTINATIONS).find(k => data.destination.toLowerCase().includes(k.toLowerCase())) || "Paris";
      setItinerary(DESTINATIONS[key]);
      setLoading(false);
      setPage("dashboard");
    }, 5000);
  };

  return (
    <>
      <style>{styles}</style>

      {/* Navbar */}
      <nav className={`navbar${scrolled ? " scrolled" : ""}`}>
        <div className="nav-logo" onClick={() => navigate("home")}>
          <div className="nav-logo-icon">🧭</div>
          <span className="nav-logo-text">Rahbar</span>
        </div>
        <div className="nav-links">
          {["home","planner","dashboard","about"].map(p => (
            <button key={p} className={`nav-link${page===p?" active":""}`} onClick={() => navigate(p)}>
              {p === "home" ? "Home" : p === "planner" ? "Plan Trip" : p === "dashboard" ? "Dashboard" : "About Us"}
            </button>
          ))}
          <button className="nav-cta" onClick={() => navigate("planner")}>Plan My Trip</button>
        </div>
        <button className="hamburger" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">
          <span/><span/><span/>
        </button>
      </nav>
      <div className={`mobile-menu${menuOpen?" open":""}`}>
        {["home","planner","dashboard","about"].map(p => (
          <button key={p} className="nav-link" onClick={() => navigate(p)}>
            {p==="home"?"Home":p==="planner"?"Plan Trip":p==="dashboard"?"Dashboard":"About Us"}
          </button>
        ))}
      </div>

      {/* Pages */}
      {page === "home" && <HomePage navigate={navigate} />}
      {page === "planner" && (loading
        ? <LoadingPage msg={loadingMessages[loadingMsg]} />
        : <PlannerPage onSubmit={handlePlanSubmit} />)}
      {page === "dashboard" && (itinerary
        ? <DashboardPage itinerary={itinerary} tripData={tripData} navigate={navigate} />
        : <EmptyDashboard navigate={navigate} />)}
      {page === "about" && <AboutPage />}

      <Footer navigate={navigate} />
    </>
  );
}

// ─── HOME PAGE ───
function HomePage({ navigate }) {
  return (
    <main>
      {/* Hero */}
      <section className="hero">
        <div className="hero-bg"/>
        <div className="hero-pattern"/>
        <div className="hero-content page-enter">
          <div>
            <div className="hero-tag">✈️ &nbsp; AI-Powered Travel Intelligence</div>
            <h1 className="hero-title">
              Your <em>Smart</em><br/>Travel<br/>Companion
            </h1>
            <p className="hero-subtitle">
              Rahbar plans your entire trip — from personalized itineraries and smart budgets to real-time alerts and cultural guidance. Travel smarter, not harder.
            </p>
            <div className="hero-btns">
              <button className="btn-primary" onClick={() => navigate("planner")}>
                Plan Your Trip <Icon name="arrow" size={16}/>
              </button>
              <button className="btn-secondary" onClick={() => navigate("dashboard")}>
                See Demo Dashboard
              </button>
            </div>
            <div className="hero-stats">
              <div className="hero-stat">
                <div className="hero-stat-num">50+</div>
                <div className="hero-stat-label">Destinations</div>
              </div>
              <div className="hero-stat">
                <div className="hero-stat-num">AI</div>
                <div className="hero-stat-label">Powered Plans</div>
              </div>
              <div className="hero-stat">
                <div className="hero-stat-num">24/7</div>
                <div className="hero-stat-label">Real-Time Alerts</div>
              </div>
            </div>
          </div>
          <div className="hero-visual">
            <div className="hero-card-main">
              <div className="hero-card-dest">
                <span className="dest-emoji">🗼</span>
                <div>
                  <div className="dest-name">Paris, France</div>
                  <span className="dest-tag">3-Day Itinerary</span>
                </div>
              </div>
              <div className="hero-card-route">
                {["Eiffel Tower & Seine Cruise","Louvre Museum & Marais","Versailles Day Trip"].map((r,i) => (
                  <div key={i} className="route-item">
                    <div className="route-dot"/>
                    <div>
                      <div>{r}</div>
                      <div className="route-label">Day {i+1}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="hero-weather">
                <div className="weather-chip"><strong>22°C</strong>Sunny</div>
                <div className="weather-chip"><strong>PKR</strong>100K Budget</div>
                <div className="weather-chip"><strong>4.9⭐</strong>Rated</div>
              </div>
            </div>
            <div className="hero-card-float float-1">
              <span className="float-icon">🛡️</span> Flight alert: On time
            </div>
            <div className="hero-card-float float-2">
              <span className="float-icon">💡</span> Cultural tip ready
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <div style={{background: "white", padding: "1px 0"}}>
        <div className="section">
          <div className="section-tag">✦ &nbsp; What Rahbar Does</div>
          <h2 className="section-title">Everything You Need,<br/>Before You Even Ask</h2>
          <p className="section-sub">Six intelligent modules working in harmony to make every journey seamless, budget-friendly, and culturally rich.</p>
          <div className="features-grid">
            {FEATURES.map((f, i) => (
              <div key={i} className="feature-card" style={{animationDelay: `${i*0.08}s`}}>
                <div className="feature-icon" style={{background: f.color}}>{f.icon}</div>
                <div className="feature-title display">{f.title}</div>
                <div className="feature-desc">{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* How it works */}
      <div className="how-bg">
        <div className="how-section">
          <div className="section-tag">✦ &nbsp; How It Works</div>
          <h2 className="section-title">From Idea to Itinerary<br/>in 4 Simple Steps</h2>
          <p className="section-sub" style={{marginBottom:"3rem"}}>Rahbar's intelligent pipeline transforms your travel dreams into detailed, actionable plans.</p>
          <div className="steps-grid">
            {[
              { n:"01", t:"Tell Us Your Preferences", d:"Share your destination, budget, dates, and interests — Rahbar does the rest." },
              { n:"02", t:"AI Generates Your Plan", d:"Our LLM engine creates a day-by-day itinerary tailored specifically to you." },
              { n:"03", t:"Review & Customize", d:"Browse your itinerary, packing list, budget breakdown, and cultural tips." },
              { n:"04", t:"Download & Travel", d:"Export your full travel plan as a file and head out with total confidence." },
            ].map((s,i) => (
              <div key={i} className="step-card">
                <div className="step-num">{s.n}</div>
                <div className="step-title">{s.t}</div>
                <div className="step-desc">{s.d}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Destinations */}
      <div className="section">
        <div className="section-tag">✦ &nbsp; Featured Destinations</div>
        <h2 className="section-title">Popular Destinations<br/>Ready to Explore</h2>
        <p className="section-sub">Click any destination to preview its pre-built intelligent itinerary.</p>
        <div className="dest-grid">
          {Object.entries(DESTINATIONS).map(([name, data]) => (
            <div key={name} className="dest-card" onClick={() => navigate("planner")}>
              <span className="dest-card-emoji">{data.emoji}</span>
              <div className="dest-card-name display">{name}</div>
              <div className="dest-card-tag">{data.days.length}-Day Itinerary</div>
              <div className="dest-card-badge">Explore →</div>
            </div>
          ))}
        </div>
      </div>

      {/* CTA Banner */}
      <div style={{background: "linear-gradient(135deg, #1A1207 0%, #2d1f0a 100%)", padding: "4rem 2rem", textAlign:"center"}}>
        <h2 style={{fontFamily:"Playfair Display,serif", fontSize:"clamp(2rem,4vw,2.8rem)", color:"white", marginBottom:"1rem"}}>
          Ready for Your Next Adventure?
        </h2>
        <p style={{color:"rgba(255,255,255,0.5)", marginBottom:"2rem", fontSize:"1.05rem"}}>
          Let Rahbar build your perfect trip — personalized, intelligent, stress-free.
        </p>
        <button className="btn-primary" style={{display:"inline-flex", margin:"0 auto"}} onClick={() => navigate("planner")}>
          Start Planning Now <Icon name="arrow" size={16}/>
        </button>
      </div>
    </main>
  );
}

// ─── PLANNER PAGE ───
function PlannerPage({ onSubmit }) {
  const [form, setForm] = useState({ destination: "", budget: "", startDate: "", endDate: "", travelers: "2", accommodation: "hotel", interests: [] });
  const [errors, setErrors] = useState({});

  const set = (k, v) => setForm(f => ({...f, [k]: v}));
  const toggleInterest = (i) => {
    setForm(f => ({ ...f, interests: f.interests.includes(i) ? f.interests.filter(x=>x!==i) : [...f.interests, i] }));
  };

  const validate = () => {
    const e = {};
    if (!form.destination.trim()) e.destination = "Please enter a destination";
    if (!form.budget || isNaN(form.budget)) e.budget = "Please enter a valid budget";
    if (!form.startDate) e.startDate = "Please select a start date";
    if (!form.endDate) e.endDate = "Please select an end date";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (validate()) onSubmit({ ...form, interests: form.interests.join(", ") || "General travel" });
  };

  return (
    <div className="planner-page page-enter">
      <div className="planner-container">
        <div className="planner-header">
          <div className="section-tag" style={{margin:"0 auto 1rem", display:"inline-flex"}}>✦ &nbsp; Trip Planner</div>
          <h1 className="section-title" style={{margin:"0 0 0.5rem"}}>Plan Your Perfect Trip</h1>
          <p style={{color:"var(--muted)", fontSize:"0.95rem"}}>Fill in your preferences and Rahbar will generate a personalized itinerary in seconds.</p>
        </div>
        <div className="form-card">
          <form onSubmit={handleSubmit}>
            <div className="form-grid">
              <div className="form-group full">
                <label className="form-label">🌍 Destination</label>
                <input className="form-input" placeholder="e.g. Paris, Istanbul, Dubai, Lahore..." value={form.destination} onChange={e=>set("destination",e.target.value)} />
                {errors.destination && <span style={{fontSize:"0.78rem",color:"var(--terracotta)"}}>{errors.destination}</span>}
              </div>
              <div className="form-group">
                <label className="form-label">💰 Budget (PKR)</label>
                <input className="form-input" type="number" placeholder="e.g. 100000" value={form.budget} onChange={e=>set("budget",e.target.value)} />
                {errors.budget && <span style={{fontSize:"0.78rem",color:"var(--terracotta)"}}>{errors.budget}</span>}
              </div>
              <div className="form-group">
                <label className="form-label">👥 Travelers</label>
                <select className="form-select" value={form.travelers} onChange={e=>set("travelers",e.target.value)}>
                  {["1","2","3","4","5+"].map(n => <option key={n} value={n}>{n} Traveler{n!=="1"?"s":""}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">📅 Start Date</label>
                <input className="form-input" type="date" value={form.startDate} onChange={e=>set("startDate",e.target.value)} />
                {errors.startDate && <span style={{fontSize:"0.78rem",color:"var(--terracotta)"}}>{errors.startDate}</span>}
              </div>
              <div className="form-group">
                <label className="form-label">📅 End Date</label>
                <input className="form-input" type="date" value={form.endDate} onChange={e=>set("endDate",e.target.value)} />
                {errors.endDate && <span style={{fontSize:"0.78rem",color:"var(--terracotta)"}}>{errors.endDate}</span>}
              </div>
              <div className="form-group full">
                <label className="form-label">🏨 Accommodation Type</label>
                <select className="form-select" value={form.accommodation} onChange={e=>set("accommodation",e.target.value)}>
                  {["Hotel","Airbnb / Apartment","Hostel","Resort","Boutique Hotel","Budget Inn"].map(a => <option key={a} value={a.toLowerCase()}>{a}</option>)}
                </select>
              </div>
              <div className="form-group full">
                <label className="form-label">✨ Interests (select all that apply)</label>
                <div className="interest-chips">
                  {INTERESTS.map(i => (
                    <button type="button" key={i} className={`chip${form.interests.includes(i)?" selected":""}`} onClick={()=>toggleInterest(i)}>{i}</button>
                  ))}
                </div>
              </div>
            </div>
            <button type="submit" className="form-submit">
              <span>🚀</span> Generate My Itinerary
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

// ─── LOADING PAGE ───
function LoadingPage({ msg }) {
  return (
    <div className="planner-page" style={{display:"flex",alignItems:"center",justifyContent:"center"}}>
      <div className="loading-overlay">
        <div className="spinner"/>
        <div className="loading-text display">Rahbar is thinking…</div>
        <div className="loading-sub">{msg}</div>
        <div className="loading-steps">
          <div className="loading-dot"/><div className="loading-dot"/><div className="loading-dot"/>
        </div>
      </div>
    </div>
  );
}

// ─── EMPTY DASHBOARD ───
function EmptyDashboard({ navigate }) {
  return (
    <div className="dashboard-page page-enter" style={{display:"flex",alignItems:"center",justifyContent:"center"}}>
      <div style={{textAlign:"center",padding:"4rem 2rem"}}>
        <div style={{fontSize:"4rem",marginBottom:"1rem"}}>🧭</div>
        <h2 className="display" style={{fontSize:"1.8rem",marginBottom:"0.8rem"}}>No Itinerary Yet</h2>
        <p style={{color:"var(--muted)",marginBottom:"2rem"}}>Plan your first trip and your personalized dashboard will appear here.</p>
        <button className="btn-primary" onClick={()=>navigate("planner")}>Plan a Trip <Icon name="arrow" size={16}/></button>
      </div>
    </div>
  );
}

// ─── DASHBOARD PAGE ───
function DashboardPage({ itinerary, tripData, navigate }) {
  const totalBudget = itinerary.budget.reduce((a,b) => a+b.amount, 0);

  return (
    <div className="dashboard-page page-enter">
      <div className="dashboard-container">
        <div className="dashboard-header">
          <div>
            <div className="section-tag" style={{marginBottom:"0.5rem",display:"inline-flex"}}>✦ &nbsp; Your Itinerary</div>
            <h1 className="dashboard-title display">{itinerary.emoji} {tripData?.destination || "Paris"}</h1>
            <div className="dashboard-sub">
              {tripData?.startDate} → {tripData?.endDate} &nbsp;·&nbsp; PKR {Number(tripData?.budget).toLocaleString()} budget &nbsp;·&nbsp; {tripData?.travelers} travelers
            </div>
          </div>
          <button className="download-btn" onClick={()=>generatePDF(itinerary, tripData)}>
            <Icon name="download" size={16}/> Download Plan
          </button>
        </div>

        {/* Alert Banner */}
        <div className="alert-banner">
          <span className="alert-icon">⚠️</span>
          <div>
            <strong style={{fontSize:"0.88rem"}}>Heads up!</strong> Weather forecast shows light rain on Day 2. Rahbar suggests carrying an umbrella and has adjusted outdoor timing. <span style={{color:"var(--amber)",fontWeight:600,cursor:"pointer"}}>View alternatives →</span>
          </div>
        </div>

        <div className="dashboard-grid">
          {/* Left Column */}
          <div style={{display:"flex",flexDirection:"column",gap:"1.5rem"}}>
            {/* Itinerary */}
            <div className="panel">
              <div className="panel-title display">📅 Day-by-Day Itinerary</div>
              {itinerary.days.map((day, i) => (
                <div key={i} className="day-block">
                  <div className="day-label">{day.title}</div>
                  {day.activities.map((act, j) => (
                    <div key={j} className="activity-item">
                      <div className="activity-dot"/>
                      {act}
                    </div>
                  ))}
                </div>
              ))}
            </div>

            {/* Packing */}
            <div className="panel">
              <div className="panel-title display">🧳 Smart Packing List</div>
              {itinerary.packing.map((p, i) => (
                <div key={i} className="pack-item">
                  <span className="pack-check">✓</span> {p}
                </div>
              ))}
            </div>
          </div>

          {/* Right Column */}
          <div style={{display:"flex",flexDirection:"column",gap:"1.5rem"}}>
            {/* Budget */}
            <div className="panel">
              <div className="panel-title display">💰 Budget Breakdown</div>
              {itinerary.budget.map((b, i) => (
                <div key={i} className="budget-item">
                  <span className="budget-label">{b.label}</span>
                  <span className="budget-amount">PKR {b.amount.toLocaleString()}</span>
                </div>
              ))}
              <div style={{height:"8px",borderRadius:"4px",background:"var(--sand)",margin:"1rem 0 0.3rem",overflow:"hidden"}}>
                <div style={{height:"100%",width:"85%",borderRadius:"4px",background:"linear-gradient(90deg,var(--amber),var(--terracotta))",transition:"width 1s ease"}}/>
              </div>
              <div style={{fontSize:"0.75rem",color:"var(--muted)",marginBottom:"0.5rem"}}>85% of budget allocated</div>
              <div className="budget-total">
                <span>Total Estimated Cost</span>
                <span style={{color:"var(--amber)"}}>PKR {totalBudget.toLocaleString()}</span>
              </div>
            </div>

            {/* Cultural Tips */}
            <div className="panel">
              <div className="panel-title display">🌍 Cultural Tips & Phrases</div>
              {itinerary.culturalTips.map((t, i) => (
                <div key={i} className="tip-item">
                  <span className="tip-arrow">→</span> {t}
                </div>
              ))}
            </div>

            <button className="new-plan-btn" onClick={()=>navigate("planner")}>
              ✦ Plan Another Trip
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── ABOUT US PAGE ───
function AboutPage() {
  return (
    <div className="planner-page page-enter" style={{minHeight:"100vh",paddingTop:"70px",background:"var(--cream)"}}>
      <div className="planner-container">
        <div className="section-tag" style={{margin:"0 auto 1rem", display:"inline-flex"}}>✦ &nbsp; About Us</div>
        <h1 className="section-title">About Rahbar</h1>
        <p className="section-sub">Rahbar is developed by Muhammad Mahaz Noor as a smart travel companion that turns your destination ideas into tailored day-by-day itineraries, intelligent budgets, and culture-aware travel guidance.</p>

        <div className="form-card" style={{padding:"2.5rem", marginTop:"2rem"}}>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"2rem"}}>
            <div>
              <h2 className="display" style={{fontSize:"1.5rem",marginBottom:"1rem"}}>Developer</h2>
              <p style={{color:"var(--muted)",lineHeight:"1.8"}}><strong>Muhammad Mahaz Noor</strong> developed this project to make travel planning simpler, smarter, and more intuitive for every user.</p>
            </div>
            <div>
              <h2 className="display" style={{fontSize:"1.5rem",marginBottom:"1rem"}}>Mission</h2>
              <p style={{color:"var(--muted)",lineHeight:"1.8"}}>Our mission is to combine modern AI with real travel insights so every journey feels prepared, personal, and stress-free.</p>
            </div>
          </div>

          <div style={{marginTop:"2rem"}}>
            <h3 className="display" style={{fontSize:"1.3rem",marginBottom:"1rem"}}>Key Highlights</h3>
            <ul style={{color:"var(--muted)",lineHeight:"1.8",listStyle:"disc inside"}}>
              <li>Personalized itinerary generation</li>
              <li>Smart budget planning</li>
              <li>Destination-specific cultural tips</li>
              <li>Travel-ready packing guidance</li>
              <li>Designed and developed by Muhammad Mahaz Noor</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── FOOTER ───
function Footer({ navigate }) {
  return (
    <footer className="footer">
      <div className="footer-inner">
        <div className="footer-top">
          <div className="footer-brand">
            <div className="nav-logo" style={{marginBottom:"0.8rem"}}>
              <div className="nav-logo-icon">🧭</div>
              <span className="nav-logo-text" style={{color:"white"}}>Rahbar</span>
            </div>
            <p>Smart Travel Companion — your AI-powered personal travel guide that makes every journey smooth, efficient, and enjoyable.</p>
          </div>
          <div className="footer-col">
            <h4>Navigation</h4>
            {[["home","Home"],["planner","Plan Trip"],["dashboard","Dashboard"],["about","About Us"]].map(([p,l]) => (
              <span key={p} className="footer-link" onClick={()=>navigate(p)}>{l}</span>
            ))}
          </div>
          <div className="footer-col">
            <h4>Technology</h4>
            {["OpenStreetMap API","OpenWeatherMap API","Aviation Edge API","Large Language Models","React.js Frontend"].map(t => (
              <span key={t} className="footer-link">{t}</span>
            ))}
          </div>
        </div>
        <div className="footer-bottom">
          <div className="footer-copy">© 2025 Rahbar – Smart Travel Companion. Final Year Project.</div>
          <div className="footer-badges">
            <span className="footer-badge">AI-Powered</span>
            <span className="footer-badge">React.js</span>
            <span className="footer-badge">Made in Pakistan 🇵🇰</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
